// Generated by https://quicktype.io

export interface ProductoDesc {
  categoria?:  string;
  desc1?:      string;
  desc2?:      string;
  producto?:   string;
  resumen?:    string;
  subtitulo1?: string;
  subtitulo2?: string;
}
